#!/bin/sh
#
# HCsCR is a third-party mod for Minecraft Java Edition
# that allows removing the end crystals faster.
#
# Copyright (c) 2023 Offenderify
# Copyright (c) 2023-2026 VidTu
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

# Fail on error, fail on unbound variable, pipefail mode.
set -euo pipefail

# Iterate.
echo "SCRIPT: Launching all versions..."
for folder in versions/*; do
    # Extract the version (only the folder name) from the full relative path.
    version=$(basename -- "${folder}")

    # Skip if ".ignored" exists.
    [ -f "${folder}/.ignored" ] && echo "SCRIPT: Skipping '${version}' because of the '.ignored' file." && continue

    # Launch.
    echo "SCRIPT: Launching '${version}'..."
    ./gradlew "-Dru.vidtu.hcscr.only=${version}" "${version}:runClient" && true
    exit="${?}"
    echo "SCRIPT: Launch for '${version}' exited with code ${exit}."
    [ "${exit}" -ne 0 ] && read -srn1 -p "SCRIPT: Non-zero exit code. Press any key to continue." exit && echo
done
echo "SCRIPT: Done launching all versions."
