#!/usr/bin/env bash
# HCsCR is a third-party mod for Minecraft Java Edition
# that allows removing the end crystals faster.
#
# Copyright (c) 2023 Offenderify
# Copyright (c) 2023-2025 VidTu
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

for ver in $(ls versions); do
    echo "> Switching to $ver..."
    ./gradlew "Set active project to $ver" --no-configuration-cache
    echo "> Launching $ver..."
    ./gradlew "${ver}:runClient" --no-configuration-cache
done

echo "> Resetting..."
./gradlew "Reset active project" --no-configuration-cache
