#!/bin/sh
#
# HCsCR is a third-party mod for Minecraft Java Edition
# that allows removing the end crystals faster.
#
# Copyright (c) 2023 Offenderify
# Copyright (c) 2023-2026 VidTu
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

# Fail on error, fail on unbound variable, pipefail mode.
set -euo pipefail

# Check args.
if [ "${#}" -eq 0 ]; then
    echo 'SCRIPT: You must specify the version to switch.'
    echo 'Example: ./switch 1.20.1-fabric'
    exit 2
fi

# Switch.
echo "SCRIPT: Switching to '${1}'..."
./gradlew "Set active project to ${1}" && true
echo "SCRIPT: Switching to '${1}' exited with code ${?}."
