# HCsCR is a third-party mod for Minecraft Java Edition
# that allows removing the end crystals faster.
#
# Copyright (c) 2023 Offenderify
# Copyright (c) 2023-2025 VidTu
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

modLoader = "javafml"
loaderVersion = "*"
license = "Apache-2.0"
issueTrackerURL = "https://github.com/VidTu/HCsCR/issues"
clientSideOnly = true

[[mods]]
modId = "hcscr"
version = "${version}"
displayName = "HCsCR"
updateJSONURL = "https://raw.githubusercontent.com/VidTu/HCsCR/main/updater_hcscr_neoforge.json"
displayURL = "https://github.com/VidTu/HCsCR"
issueTrackerURL = "https://github.com/VidTu/HCsCR/issues"
catalogueImageIcon = "hcscr_64.png"
catalogueItemIcon = "minecraft:end_crystal"
catalogueBackground = "hcscr_background.png"
itemIcon = "minecraft:end_crystal"
logoFile = "hcscr_240.png"
credits = "Offenderify"
authors = "VidTu"
displayTest = "IGNORE_ALL_VERSION"
description = '''Remove your end crystals before the server even knows you hit 'em!'''

[[mixins]]
config = "hcscr.mixins.json"

[[dependencies.hcscr]]
modId = "minecraft"
type = "required"
mandatory = true
versionRange = "[${minecraft}]"
ordering = "NONE"
side = "CLIENT"

[[dependencies.hcscr]]
modId = "${platform}"
type = "required"
mandatory = true
versionRange = "*"
ordering = "NONE"
side = "CLIENT"

[modproperties.hcscr]
catalogueImageIcon = "hcscr_64.png"
catalogueItemIcon = "minecraft:end_crystal"
catalogueBackground = "hcscr_background.png"
itemIcon = "minecraft:end_crystal"
logoFile = "hcscr_240.png"
