modLoader = "javafml"
loaderVersion = "*"
license = "Apache-2.0"
issueTrackerURL = "https://github.com/VidTu/HCsCR/issues"
clientSideOnly = true

[[mods]]
modId = "hcscr"
version = "${version}"
displayName = "HCsCR"
updateJSONURL = "https://raw.githubusercontent.com/VidTu/HCsCR/main/updater_hcscr_neoforge.json"
displayURL = "https://github.com/VidTu/HCsCR"
issueTrackerURL = "https://github.com/VidTu/HCsCR/issues"
catalogueImageIcon = "hcscr_64.png"
catalogueItemIcon = "minecraft:end_crystal"
catalogueBackground = "hcscr_background.png"
itemIcon = "minecraft:end_crystal"
logoFile = "hcscr_240.png"
credits = "Offenderify"
authors = "VidTu"
displayTest = "IGNORE_ALL_VERSION"
description = '''Remove your end crystals before the server even knows you hit 'em!'''

[[mixins]]
config = "hcscr.mixins.json"

[[dependencies.hcscr]]
modId = "minecraft"
type = "required"
mandatory = true
versionRange = "[${minecraft}]"
ordering = "NONE"
side = "CLIENT"

[[dependencies.hcscr]]
modId = "${platform}"
type = "required"
mandatory = true
versionRange = "*"
ordering = "NONE"
side = "CLIENT"
