# HCsCR is a third-party mod for Minecraft Java Edition
# that allows removing the end crystals faster.
#
# Copyright (c) 2023 Offenderify
# Copyright (c) 2023-2026 VidTu
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0
#
# List of Mojang classe names mapped to MCP class names.
# Incomplete mappings, only those used by HCsCR are replaced.
# Used ONLY by Forge 1.16.5. (maybe we just should drop support?)
com.mojang.blaze3d.platform.InputConstants=net.minecraft.client.util.InputMappings
com.mojang.blaze3d.vertex.PoseStack=com.mojang.blaze3d.matrix.MatrixStack
net.minecraft.ChatFormatting=net.minecraft.util.text.TextFormatting
net.minecraft.client.KeyMapping=net.minecraft.client.settings.KeyBinding
net.minecraft.client.gui.Font=net.minecraft.client.gui.FontRenderer
net.minecraft.client.gui.components.AbstractSliderButton=net.minecraft.client.gui.widget.AbstractSlider
net.minecraft.client.gui.components.AbstractWidget=net.minecraft.client.gui.widget.Widget
net.minecraft.client.gui.components.Button=net.minecraft.client.gui.widget.button.Button
net.minecraft.client.gui.components.Checkbox=net.minecraft.client.gui.widget.button.CheckboxButton
net.minecraft.client.gui.screens.Screen=net.minecraft.client.gui.screen.Screen
net.minecraft.client.multiplayer.ClientLevel=net.minecraft.client.world.ClientWorld
net.minecraft.client.multiplayer.ClientPacketListener=net.minecraft.client.network.play.ClientPlayNetHandler
net.minecraft.client.player.LocalPlayer=net.minecraft.client.entity.player.ClientPlayerEntity
net.minecraft.client.resources.sounds.SimpleSoundInstance=net.minecraft.client.audio.SimpleSound
net.minecraft.core.BlockPos=net.minecraft.util.math.BlockPos
net.minecraft.network.Connection=net.minecraft.network.NetworkManager
net.minecraft.network.chat.CommonComponents=net.minecraft.client.gui.DialogTexts
net.minecraft.network.chat.Component=net.minecraft.util.text.ITextComponent
net.minecraft.network.chat.MutableComponent=net.minecraft.util.text.IFormattableTextComponent
net.minecraft.network.chat.TranslatableComponent=net.minecraft.util.text.TranslationTextComponent
net.minecraft.network.protocol.game.ClientboundBlockUpdatePacket=net.minecraft.network.play.server.SChangeBlockPacket
net.minecraft.resources.ResourceLocation=net.minecraft.util.ResourceLocation
net.minecraft.sounds.SoundEvents=net.minecraft.util.SoundEvents
net.minecraft.util.FormattedCharSequence=net.minecraft.util.IReorderingProcessor
net.minecraft.util.Mth=net.minecraft.util.math.MathHelper
net.minecraft.util.profiling.ProfilerFiller=net.minecraft.profiler.IProfiler
net.minecraft.util.thread.ReentrantBlockableEventLoop=net.minecraft.util.concurrent.RecursiveEventLoop
net.minecraft.world.InteractionHand=net.minecraft.util.Hand
net.minecraft.world.InteractionResult=net.minecraft.util.ActionResultType
net.minecraft.world.damagesource.DamageSource=net.minecraft.util.DamageSource
net.minecraft.world.effect.MobEffectInstance=net.minecraft.potion.EffectInstance
net.minecraft.world.entity.Entity=net.minecraft.entity.Entity
net.minecraft.world.entity.ai.attributes.AttributeMap=net.minecraft.entity.ai.attributes.AttributeModifierManager
net.minecraft.world.entity.ai.attributes.Attributes=net.minecraft.entity.ai.attributes.Attributes
net.minecraft.world.entity.boss.enderdragon.EndCrystal=net.minecraft.entity.item.EnderCrystalEntity
net.minecraft.world.entity.monster.Slime=net.minecraft.entity.monster.SlimeEntity
net.minecraft.world.entity.player.Player=net.minecraft.entity.player.PlayerEntity
net.minecraft.world.item.ItemStack=net.minecraft.item.ItemStack
net.minecraft.world.level.BlockGetter=net.minecraft.world.IBlockReader
net.minecraft.world.level.Level=net.minecraft.world.World
net.minecraft.world.level.block.BedBlock=net.minecraft.block.BedBlock
net.minecraft.world.level.block.RespawnAnchorBlock=net.minecraft.block.RespawnAnchorBlock
net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase=net.minecraft.block.AbstractBlock$AbstractBlockState
net.minecraft.world.level.block.state.BlockBehaviour=net.minecraft.block.AbstractBlock
net.minecraft.world.level.block.state.BlockState=net.minecraft.block.BlockState
net.minecraft.world.phys.AABB=net.minecraft.util.math.AxisAlignedBB
net.minecraft.world.phys.BlockHitResult=net.minecraft.util.math.BlockRayTraceResult
net.minecraft.world.phys.shapes.CollisionContext=net.minecraft.util.math.shapes.ISelectionContext
net.minecraft.world.phys.shapes.EntityCollisionContext=net.minecraft.util.math.shapes.EntitySelectionContext
net.minecraft.world.phys.shapes.Shapes=net.minecraft.util.math.shapes.VoxelShapes
net.minecraft.world.phys.shapes.VoxelShape=net.minecraft.util.math.shapes.VoxelShape
