/*
 * HCsCR is a third-party mod for Minecraft Java Edition
 * that allows removing the end crystals faster.
 *
 * Copyright (c) 2023 Offenderify
 * Copyright (c) 2023-2026 VidTu
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

package ru.vidtu.hcscr;

import it.unimi.dsi.fastutil.objects.Object2IntMap;
import it.unimi.dsi.fastutil.objects.Object2LongArrayMap;
import it.unimi.dsi.fastutil.objects.Object2LongMap;
import it.unimi.dsi.fastutil.objects.Object2ObjectArrayMap;
import it.unimi.dsi.fastutil.objects.Object2ObjectMap;
import it.unimi.dsi.fastutil.objects.ObjectIterator;
import net.minecraft.client.Minecraft;
import net.minecraft.client.multiplayer.ClientLevel;
import net.minecraft.client.player.LocalPlayer;
import net.minecraft.core.BlockPos;
import net.minecraft.util.profiling.ProfilerFiller;
import net.minecraft.world.damagesource.DamageSource;
import net.minecraft.world.effect.MobEffectInstance;
import net.minecraft.world.entity.Entity;
import net.minecraft.world.entity.ai.attributes.AttributeMap;
import net.minecraft.world.entity.ai.attributes.Attributes;
import net.minecraft.world.entity.player.Player;
import net.minecraft.world.level.block.state.BlockState;
import net.minecraft.world.phys.AABB;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.apache.logging.log4j.Marker;
import org.apache.logging.log4j.MarkerManager;
import org.jetbrains.annotations.ApiStatus;
import org.jetbrains.annotations.Contract;
import org.jetbrains.annotations.UnknownNullability;
import org.jspecify.annotations.NullMarked;
import ru.vidtu.hcscr.compile.Variables;
import ru.vidtu.hcscr.config.Config;
import ru.vidtu.hcscr.config.CrystalMode;
import ru.vidtu.hcscr.handler.KeyHandler;
import ru.vidtu.hcscr.mixin.block.BlockBehaviour_BlockStateBaseMixin;
import ru.vidtu.hcscr.mixin.crystal.EntityMixin;
import ru.vidtu.hcscr.platform.HStonecutter;

import java.util.Iterator;
import java.util.List;
import java.util.Map;

/**
 * Main HCsCR class.
 *
 * @author VidTu
 * @apiNote Internal use only
 */
@ApiStatus.Internal
@NullMarked
public final class HCsCR {
    /**
     * Marker for all logs generated by the mod.
     */
    @UnknownNullability
    public static final Marker MARKER = (Variables.DEBUG_LOGS ? MarkerManager.getMarker("MOD_HCSCR") : null);

    /**
     * Hit entities mapped to their time of removal/hiding time in units of {@link System#nanoTime()}.
     * <p>
     * As soon as current time will reach the removal time, {@link #handleClientMainLoop(Minecraft)}
     * will either remove them via {@link HStonecutter#removeEntity(Entity)} or mark them
     * as hidden entities into {@link #HIDDEN_ENTITIES}.
     *
     * @see #handleClientMainLoop(Minecraft)
     * @see HStonecutter#removeEntity(Entity)
     * @see #HIDDEN_ENTITIES
     */
    // This map is not expected to grow more than a few elements, so it's an array-baked map, not a hash-baked one.
    // Moreover, it's being iterated linearly anyway in handleFrame(...).
    public static final Object2LongMap<Entity> SCHEDULED_ENTITIES = new Object2LongArrayMap<>(0);

    /**
     * Hidden entities mapped to their remaining resync game ticks.
     * <p>
     * These entities won't appear in the world as their
     * hitbox will be removed via {@link EntityMixin}.
     * <p>
     * They are counted down in {@link #cleanHiddenEntities(Minecraft, ProfilerFiller)}.
     *
     * @see EntityMixin
     * @see #cleanHiddenEntities(Minecraft, ProfilerFiller)
     * @see HStonecutter#linearRemovableInt2ObjectMap()
     */
    // This map should array-backed too, but it must support setValue(int) in iterators, so sometimes it's a hash-backed
    // map, even when it's suboptimal. See HStonecutter.linearRemovableInt2ObjectMap() for details.
    public static final Object2IntMap<Entity> HIDDEN_ENTITIES = HStonecutter.linearRemovableInt2ObjectMap();

    /**
     * A map of block positions that the player won't
     * collide with mapped to expected block states.
     * <p>
     * These blocks won't collide with the player in the world as
     * their hitbox will be removed via {@link BlockBehaviour_BlockStateBaseMixin}.
     * <p>
     * The validity is checked in {@link #cleanClippingBlocks(Minecraft, ProfilerFiller)}.
     *
     * @see BlockBehaviour_BlockStateBaseMixin
     * @see #cleanClippingBlocks(Minecraft, ProfilerFiller)
     */
    // This map is not expected to grow more than a few elements, so it's an array-baked map, not a hash-baked one.
    // Moreover, it's being iterated linearly anyway in handleTick(...).
    public static final Object2ObjectMap<BlockPos, BlockState> CLIPPING_BLOCKS = new Object2ObjectArrayMap<>(0);

    /**
     * Logger for this class.
     */
    @UnknownNullability
    private static final Logger LOGGER = (Variables.DEBUG_LOGS ? LogManager.getLogger("HCsCR/HCsCR") : null);

    /**
     * An instance of this class cannot be created.
     *
     * @throws AssertionError Always
     * @deprecated Always throws
     */
    @ApiStatus.ScheduledForRemoval
    @Deprecated
    @Contract(value = "-> fail", pure = true)
    private HCsCR() {
        if (Variables.DEBUG_ASSERTS) {
            throw new AssertionError("HCsCR: No instances.");
        }
    }

    /**
     * Handles the client tick end.
     *
     * @param client Client game instance
     * @see #handleConfigBind(Minecraft, ProfilerFiller)
     * @see #handleToggleBind(Minecraft, ProfilerFiller)
     * @see #cleanHiddenEntities(Minecraft, ProfilerFiller)
     * @see #cleanClippingBlocks(Minecraft, ProfilerFiller)
     */
    public static void handleClientTickEnd(final Minecraft client) {
        // Validate.
        if (Variables.DEBUG_ASSERTS) {
            assert (client != null) : "HCsCR: Parameter 'client' is null.";
            assert (client.isSameThread()) : "HCsCR: Handling a client game tick end NOT from the main thread. (thread: " + Thread.currentThread() + ", client: " + client + ')';
        }

        // Get and push the profiler.
        final ProfilerFiller profiler;
        if (Variables.DEBUG_PROFILER) {
            profiler = HStonecutter.profilerOfClient(client); // Implicit NPE for 'client'
            profiler.push("hcscr:client_tick_end");
        } else {
            profiler = null;
        }

        // Keybinds.
        KeyHandler.handleKeys(client, profiler); // Implicit NPE for 'client'

        // Entities/blocks.
        cleanHiddenEntities(client, profiler); // Implicit NPE for 'client'
        cleanClippingBlocks(client, profiler); // Implicit NPE for 'client'

        // Pop the profiler.
        if (Variables.DEBUG_PROFILER) {
            profiler.pop();
        }
    }

    /**
     * Handles the client main loop. Removes redundant elements from {@link #SCHEDULED_ENTITIES}.
     *
     * @param client Client game instance
     */
    public static void handleClientMainLoop(final Minecraft client) {
        // Validate.
        if (Variables.DEBUG_ASSERTS) {
            assert (client != null) : "HCsCR: Parameter 'client' is null.";
            assert (client.isSameThread()) : "HCsCR: Handling client main loop NOT from the main thread. (thread: " + Thread.currentThread() + ", client: " + client + ')';
        }

        // Get and push the profiler.
        final ProfilerFiller profiler;
        if (Variables.DEBUG_PROFILER) {
            profiler = HStonecutter.profilerOfClient(client); // Implicit NPE for 'client'
            profiler.push("hcscr:client_main_loop");
        } else {
            profiler = null;
        }

        // Skip if there's no entities to remove.
        if (SCHEDULED_ENTITIES.isEmpty()) {
            // Pop the profiler.
            if (Variables.DEBUG_PROFILER) {
                profiler.pop();
            }

            // Stop.
            return;
        }

        // Remove all entities that have expired or no longer in the world.
        final int resync = Config.crystalsResync();
        final boolean noResync = (resync == 0);
        final long now = System.nanoTime();
        final ObjectIterator<Object2LongMap.Entry<Entity>> iterator = SCHEDULED_ENTITIES.object2LongEntrySet().iterator();
        while (iterator.hasNext()) {
            // Extract.
            final Object2LongMap.Entry<Entity> entry = iterator.next();
            final Entity entity = entry.getKey();
            final long expiry = entry.getLongValue();

            // Entity has been deleted from the world.
            if (HStonecutter.isEntityRemoved(entity)) {
                // Remove from iterator.
                iterator.remove();

                // Log. (**DEBUG**)
                if (Variables.DEBUG_LOGS && LOGGER.isDebugEnabled(MARKER)) {
                    LOGGER.debug(MARKER, "HCsCR: Forgot hit entity. (now: {}, entity: {}, expiry: {})", now, entity, expiry);
                }

                // Continue.
                continue;
            }

            // Skip if entry is still in the world and hasn't reached the timeout.
            if ((expiry - now) >= 0L) continue;

            // Remove from iterator.
            iterator.remove();

            // Hide or remove the entity.
            if (noResync) {
                //$ remove_entity entity
                entity.discard();
            } else {
                HIDDEN_ENTITIES.put(entity, resync);
            }

            // Log. (**DEBUG**)
            if (Variables.DEBUG_LOGS && LOGGER.isDebugEnabled(MARKER)) {
                LOGGER.debug(MARKER, "HCsCR: Removed/hidden hit entity. (now: {}, entity: {}, expiry: {})", now, entity, expiry);
            }
        }

        // Pop the profiler.
        if (Variables.DEBUG_PROFILER) {
            profiler.pop();
        }
    }

    /**
     * Handles the entity hit by a player. Removes the entity client-side or promotes to {@link #SCHEDULED_ENTITIES}, if required.
     *
     * @param player Player attacking the entity
     * @param entity Entity being attacked by a player
     * @param source Attack source (inaccurate if invoked on the client)
     * @param amount Total amount of damage done to the entity (inaccurate if invoked on the client)
     * @return Whether the entity has been removed
     * @see Config#enable()
     * @see Config#shouldProcess(Player, Entity)
     * @see Config#crystals()
     * @see Config#crystalsResync()
     * @see Config#crystalsDelay()
     */
    public static boolean handlePlayerHittingEntity(final Player player, final Entity entity,
                                                    final DamageSource source, final float amount) {
        // Validate.
        if (Variables.DEBUG_ASSERTS) {
            assert (player != null) : "HCsCR: Parameter 'player' is null. (entity: " + entity + ", source: " + source + ", amount: " + amount + ')';
            assert (entity != null) : "HCsCR: Parameter 'entity' is null. (player: " + player + ", source: " + source + ", amount: " + amount + ')';
            assert (source != null) : "HCsCR: Parameter 'source' is null. (player: " + player + ", entity: " + entity + ", amount: " + amount + ')';
            assert (Float.isFinite(amount)) : "HCsCR: Parameter 'amount' is not finite. (player: " + player + ", entity: " + entity + ", source: " + source + ", amount: " + amount + ')';
        }

        // Do NOT process hit if any of the following conditions is met:
        // - The current level (world) is not client-side. (e.g., integrated server world)
        // - The amount of dealt damage is zero or less.
        // - The damaged entity is already scheduled for removal.
        // - The mod is disabled via config or keybind.
        // - This entity type shouldn't be processed at all (e.g. any living entity) or by the current config (e.g. slime).
        // - The damaging entity is not a player.
        if (!HStonecutter.levelOfEntity(entity).isClientSide() || (amount <= 0.0f) || // Implicit NPE for 'entity'
                HStonecutter.isEntityRemoved(entity) || !Config.enable() ||
                !Config.shouldProcess(player, entity)) return false;

        // Validate.
        if (Variables.DEBUG_ASSERTS) {
            assert (player instanceof LocalPlayer) : "HCsCR: Source entity is not LocalPlayer. (player: " + player + ", entity: " + entity + ", source: " + source + ", amount: " + amount + ')';
            //noinspection ObjectEquality // <- Should be the same reference.
            assert ((player == source.getEntity()) && (player == source.getDirectEntity()) && (source.getEntity() == Minecraft.getInstance().player)) : "HCsCR: Source entity is not us. (player: " + player + ", entity: " + entity + ", source: " + source + ", amount: " + amount + ", sourceEntity: " + source.getEntity() + ", sourceDirectEntity: " + source.getDirectEntity() + ", mcPlayer: " + Minecraft.getInstance().player + ')';
            assert (Minecraft.getInstance().isSameThread()) : "HCsCR: Handling entity attack NOT from the main thread. (thread: " + Thread.currentThread() + ", player: " + player + ", entity: " + entity + ", source: " + source + ", amount: " + amount + ')';
        }

        // Don't process player hits that deal zero damage, e.g. with the weakness effect.
        final AttributeMap map = player.getAttributes();
        for (final MobEffectInstance instance : player.getActiveEffects()) {
            //? if >=1.20.6 {
            instance.getEffect().value().addAttributeModifiers(map, instance.getAmplifier()); // Implicit NPE for 'effect', 'map'
            //?} elif >=1.20.2 {
            /*instance.getEffect().addAttributeModifiers(map, instance.getAmplifier()); // Implicit NPE for 'effect', 'map'
            *///?} else {
            /*instance.getEffect().addAttributeModifiers(player, map, instance.getAmplifier()); // Implicit NPE for 'player', 'effect', 'map'
            *///?}
        }
        final double attributeAmount = player.getAttributeValue(Attributes.ATTACK_DAMAGE);
        for (final MobEffectInstance instance : player.getActiveEffects()) {
            //? if >=1.20.6 {
            instance.getEffect().value().removeAttributeModifiers(map); // Implicit NPE for 'effect', 'map'
            //?} elif >=1.20.2 {
            /*instance.getEffect().removeAttributeModifiers(map); // Implicit NPE for 'effect', 'map'
            *///?} else {
            /*instance.getEffect().removeAttributeModifiers(player, map, instance.getAmplifier()); // Implicit NPE for 'player', 'effect', 'map'
            *///?}
        }
        if (attributeAmount <= 0.0d) return false;

        // Fast-remove one crystal entity, if the mode is DIRECT.
        final CrystalMode mode = Config.crystals();
        if (mode == CrystalMode.DIRECT) {
            // Remove/hide the entity, if there's no delay.
            final int delay = Config.crystalsDelay();
            if (delay == 0) {
                // Remove the entity instantly, if there's no resync.
                final int resync = Config.crystalsResync();
                if (resync == 0) {
                    //$ remove_entity entity
                    entity.discard();
                    return true;
                }

                // Hide the entity.
                HIDDEN_ENTITIES.put(entity, resync);
                return true;
            }

            // Schedule the removal of the entity, if the delay exists.
            SCHEDULED_ENTITIES.putIfAbsent(entity, System.nanoTime() + delay);
            return true;
        }

        // Get the enveloped entities.
        final AABB entityBox = entity.getBoundingBox();
        final List<Entity> entities = HStonecutter.levelOfEntity(entity).getEntities(entity, entity.getBoundingBox(), (final Entity other) -> {
            // Validate.
            if (Variables.DEBUG_ASSERTS) {
                assert (other != null) : "HCsCR: Parameter 'other' is null. (entity: " + entity + ')';
            }

            // Do NOT process hit if any of the following conditions is met:
            // - The damaged entity is already scheduled for removal.
            // - This entity type shouldn't be processed at all (e.g. any living entity) or by the current config (e.g. slime).
            // - The other entity is not fully contained inside the enveloping entity.
            if (HStonecutter.isEntityRemoved(other) || !Config.shouldProcess(player, other)) return false;
            final AABB otherBox = other.getBoundingBox();
            return ((otherBox.minX >= entityBox.minX) && (otherBox.maxX <= entityBox.maxX) &&
                    (otherBox.minY >= entityBox.minY) && (otherBox.maxY <= entityBox.maxY) &&
                    (otherBox.minZ >= entityBox.minZ) && (otherBox.maxZ <= entityBox.maxZ));
        });

        // Remove/hide the entities, if there's no delay.
        final int delay = Config.crystalsDelay();
        if (delay == 0) {
            // Remove the entities instantly, if there's no resync.
            final int resync = Config.crystalsResync();
            if (resync == 0) {
                //$ remove_entity entity
                entity.discard();
                for (final Entity other : entities) {
                    //$ remove_entity other
                    other.discard();
                }
                return true;
            }

            // Hide the entity.
            HIDDEN_ENTITIES.put(entity, resync);
            for (final Entity other : entities) {
                HIDDEN_ENTITIES.put(other, resync);
            }
            return true;
        }

        // Schedule the removal of the entities, if the delay exists.
        final long removeAt = (System.nanoTime() + delay);
        SCHEDULED_ENTITIES.putIfAbsent(entity, removeAt);
        for (final Entity other : entities) {
            SCHEDULED_ENTITIES.putIfAbsent(other, removeAt);
        }
        return true;
    }

    /**
     * Cleans the hidden entities. Removes redundant entities from {@link #HIDDEN_ENTITIES} or processes them in a
     * way similar to {@link #handlePlayerHittingEntity(Player, Entity, DamageSource, float)}.
     *
     * @param client   Client game instance
     * @param profiler Client profiler
     * @see #handleClientTickEnd(Minecraft)
     * @see #HIDDEN_ENTITIES
     * @see #handlePlayerHittingEntity(Player, Entity, DamageSource, float)
     */
    private static void cleanHiddenEntities(final Minecraft client, final @UnknownNullability ProfilerFiller profiler) {
        // Validate.
        if (Variables.DEBUG_ASSERTS) {
            assert (client != null) : "HCsCR: Parameter 'client' is null. (profiler: " + profiler + ')';
            if (Variables.DEBUG_PROFILER) {
                assert (profiler != null) : "HCsCR: Parameter 'profiler' is null. (client: " + client + ')';
            }
            assert (client.isSameThread()) : "HCsCR: Cleaning hidden entities NOT from the main thread. (thread: " + Thread.currentThread() + ", client: " + client + ", profiler: " + profiler + ')';
        }

        // Push the profiler.
        if (Variables.DEBUG_PROFILER) {
            profiler.push("hcscr:clean_hidden_entities"); // Implicit NPE for 'profiler'
        }

        // Skip if no hidden entities.
        if (HIDDEN_ENTITIES.isEmpty()) {
            // Pop the profiler.
            if (Variables.DEBUG_PROFILER) {
                profiler.pop();
            }

            // Stop.
            return;
        }

        // Nuke all entities, if level is empty.
        if (client.level == null) { // Implicit NPE for 'client'
            // Log. (**TRACE**)
            if (Variables.DEBUG_LOGS) {
                LOGGER.trace(MARKER, "HCsCR: Level has been unloaded, nuking hidden entities...");
            }

            // Clear.
            HIDDEN_ENTITIES.clear();

            // Log. (**DEBUG**)
            if (Variables.DEBUG_LOGS) {
                LOGGER.debug(MARKER, "HCsCR: Level has been unloaded, nuked hidden entities.");
            }

            // Pop the profiler.
            if (Variables.DEBUG_PROFILER) {
                profiler.pop();
            }

            // Stop.
            return;
        }

        // Iterate.
        final ObjectIterator<Object2IntMap.Entry<Entity>> iterator = HIDDEN_ENTITIES.object2IntEntrySet().iterator();
        while (iterator.hasNext()) {
            // Extract.
            final Object2IntMap.Entry<Entity> entry = iterator.next();
            final Entity entity = entry.getKey();
            final int ticksBeforeResync = entry.getIntValue();

            // Log. (**TRACE**)
            if (Variables.DEBUG_LOGS && LOGGER.isTraceEnabled(MARKER)) {
                LOGGER.trace(MARKER, "HCsCR: Ticking hidden entity... (entity: {}, ticksBeforeResync: {})", entity, ticksBeforeResync);
            }

            // Entity has been removed.
            if (HStonecutter.isEntityRemoved(entity)) {
                // Remove from the map.
                iterator.remove();

                // Log. (**DEBUG**)
                if (Variables.DEBUG_LOGS && LOGGER.isDebugEnabled(MARKER)) {
                    LOGGER.debug(MARKER, "HCsCR: Removed hidden entity. (entity: {}, ticksBeforeResync: {})", entity, ticksBeforeResync);
                }

                // Continue.
                continue;
            }

            // Entity should be resynced.
            if (ticksBeforeResync <= 0) {
                // Remove  from the map.
                iterator.remove();

                // Log, continue. (**DEBUG**)
                if (Variables.DEBUG_LOGS && LOGGER.isDebugEnabled(MARKER)) {
                    LOGGER.debug(MARKER, "HCsCR: Resynced hidden entity. (entity: {}, ticksBeforeResync: {})", entity, ticksBeforeResync);
                }

                // Continue.
                continue;
            }

            // Countdown.
            entry.setValue(ticksBeforeResync - 1);
        }

        // Pop the profiler.
        if (Variables.DEBUG_PROFILER) {
            profiler.pop();
        }
    }

    /**
     * Cleans the clipping blocks. Removes redundant entries from {@link #CLIPPING_BLOCKS}.
     *
     * @param client   Client game instance
     * @param profiler Client profiler
     * @see #handleClientTickEnd(Minecraft)
     * @see #CLIPPING_BLOCKS
     */
    private static void cleanClippingBlocks(final Minecraft client, final @UnknownNullability ProfilerFiller profiler) {
        // Validate.
        if (Variables.DEBUG_ASSERTS) {
            assert (client != null) : "HCsCR: Parameter 'client' is null. (profiler: " + profiler + ')';
            if (Variables.DEBUG_PROFILER) {
                assert (profiler != null) : "HCsCR: Parameter 'profiler' is null. (client: " + client + ')';
            }
            assert (client.isSameThread()) : "HCsCR: Cleaning clipping blocks NOT from the main thread. (thread: " + Thread.currentThread() + ", client: " + client + ", profiler: " + profiler + ')';
        }

        // Push the profiler.
        if (Variables.DEBUG_PROFILER) {
            profiler.push("hcscr:clean_clipping_blocks"); // Implicit NPE for 'profiler'
        }

        // Skip if no clipping blocks.
        if (CLIPPING_BLOCKS.isEmpty()) {
            // Pop the profiler.
            if (Variables.DEBUG_PROFILER) {
                profiler.pop();
            }

            // Stop.
            return;
        }

        // Nuke all blocks, if level is empty.
        final ClientLevel level = client.level; // Implicit NPE for 'client'
        if (level == null) {
            // Log. (**TRACE**)
            if (Variables.DEBUG_LOGS) {
                LOGGER.trace(MARKER, "HCsCR: Level has been unloaded, nuking clipping blocks...");
            }

            // Clear.
            CLIPPING_BLOCKS.clear();

            // Log. (**DEBUG**)
            if (Variables.DEBUG_LOGS) {
                LOGGER.debug(MARKER, "HCsCR: Level has been unloaded, nuked clipping blocks.");
            }

            // Pop the profiler.
            if (Variables.DEBUG_PROFILER) {
                profiler.pop();
            }

            // Stop.
            return;
        }

        // Iterate.
        final Iterator<Map.Entry<BlockPos, BlockState>> iterator = CLIPPING_BLOCKS.entrySet().iterator();
        while (iterator.hasNext()) {
            // Extract.
            final Map.Entry<BlockPos, BlockState> entry = iterator.next();
            final BlockPos pos = entry.getKey();
            final BlockState expectedState = entry.getValue();

            // Log. (**TRACE**)
            if (Variables.DEBUG_LOGS) {
                LOGGER.trace(MARKER, "HCsCR: Ticking clipping block... (pos: {}, expectedState: {})", pos, expectedState);
            }

            // Skip if block is still there.
            final BlockState actualState = level.getBlockState(pos);
            if (actualState.equals(expectedState)) continue;

            // Remove from the map.
            iterator.remove();

            // Log. (**DEBUG**)
            if (Variables.DEBUG_LOGS) {
                LOGGER.debug(MARKER, "HCsCR: Removed clipping block. (pos: {}, expectedState: {}, actualState: {})", pos, expectedState, actualState);
            }
        }

        // Pop the profiler.
        if (Variables.DEBUG_PROFILER) {
            profiler.pop();
        }
    }
}
